export { HomePage } from "../pages/Home/LandingPage/LandingPage"
export { LoginPage } from "../pages/Auth/Login/Login"
export { CadastroPage } from "../pages/Auth/Cadastro/Cadastro"
export { HomePageProdutor } from "../pages/Home/Produtor/LandingPageProdutor"
export { PedidosPage } from "../pages/Pedidos/PagePedidos/Pedidos"
export { PedidoDetalhePage } from "../pages/Pedidos/PedidoDetalhes/PedidoDetalhe.tsx"
export { CadastrarProdutoPage } from "../pages/produtoCRUD/Cadastrar/CadastrarProduto.tsx"
export {ProdutoDetalhePage} from "../pages/produtoCRUD/Produtos/Produtos.tsx"
export { FinalizarCarrinhoPage } from "../pages/carrinho/FinalizarCarrinho/FinalizarCarrinho.tsx"
export { FinalizarEnderecoPage } from "../pages/carrinho/FinalizarEndereco/FinalizarEndereco.tsx"
export { ProdutorPrivatePage } from "../pages/PerfilProdutor/PerfilProdutorPrivado.tsx"
export { PerfilProdutorPage } from "../pages/PerfilProdutor/PerfilProdutorPublico.tsx"
export {EditarProdutoPage} from "../pages/produtoCRUD/editar/EditarProdutoPage.tsx"
export {ResetSenhaPage} from "../pages/Auth/resetSenha/resetSenha.tsx"
export {ResetTokenPage} from "../pages/Auth/resetToken/resetSenhaToken.tsx"
export {HomeConsumidorPage} from "../pages/Home/Consumidor/LeadingPageConsumidor.tsx"
export {CarrinhoVazioPage} from "../pages/carrinho/CarrinhoVazio/CarrinhoVazio.tsx"
export {DadosProdutor} from "../pages/dadosPessoais/Produtor/PerfilProdutor.tsx"
export {DadosConsumidor} from "../pages/dadosPessoais/Consumidor/PerfilConsumidor.tsx"

