export { HomePage } from "../pages/Home/LandingPage/LandingPage"
export { LoginPage } from "../pages/Auth/Login/Login"
export { CadastroPage } from "../pages/Auth/Cadastro/Cadastro"
export { HomePageProdutor } from "../pages/Home/Produtor/LandingPageProdutor"
export { PedidosPage } from "../pages/Pedidos/Pedidos"
