export { HomePage } from "../pages/Home/LandingPage/LandingPage"
export { LoginPage } from "../pages/Auth/Login/Login"
export { CadastroPage } from "../pages/Auth/Cadastro/Cadastro"
export { HomePageProdutor } from "../pages/Home/Produtor/LandingPageProdutor"
export { PedidosPage } from "../pages/Pedidos/PagePedidos/Pedidos"
export { PedidoDetalhe } from "../pages/Pedidos/PedidoDetalhes/PedidoDetalhe.tsx"
export { CadastrarProdutoPage } from "../pages/Cadastrar/CadastrarProduto.tsx"
export { ProdutoDetalhePage } from "../pages/Produtos/Produtos.tsx"
export { FinalizarCarrinhoPage } from "../pages/carrinho/FinalizarCarrinho/FinalizarCarrinho.tsx"
export { FinalizarEnderecoPage } from "../pages/carrinho/FinalizarEndereco/FinalizarEndereco.tsx"
export { ProdutorPrivatePage } from "../pages/PerfilProdutor/PerfilProdutorPrivado.tsx"
export { PerfilProdutorPage } from "../pages/PerfilProdutor/PerfilProdutorPublico.tsx"
export {EditarProdutoPage} from "../pages/editar/EditarProdutoPage.tsx"
export {ResetSenhaPage} from "../pages/Auth/resetSenha/resetSenha.tsx"
export {ResetTokenPage} from "../pages/Auth/resetToken/resetSenhaToken.tsx"